config/routes.rb
Rails.application.routes.draw do
  resources :audio_channels

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_channel.rb
class AudioChannel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audio_channels_controller.rb
class AudioChannelsController < ApplicationController
  before_action :set_audio_channel, only: %i[ show edit update destroy ]

  # GET /audio_channels or /audio_channels.json
  def index
    @audio_channels = AudioChannel.all
  end

  # GET /audio_channels/1 or /audio_channels/1.json
  def show
  end

  # GET /audio_channels/new
  def new
    @audio_channel = AudioChannel.new
  end

  # GET /audio_channels/1/edit
  def edit

  end

  # POST /audio_channels or /audio_channels.json
  def create
    @audio_channel = AudioChannel.new(audio_channel_params)
    enteredNumber = @audio_channel.chNumber
    #create_mcast_ip(enteredNumber)
    @audio_channel.update(chMcastIP: create_mcast_ip(enteredNumber))

    respond_to do |format|
      if @audio_channel.save
        format.html { redirect_to @audio_channel, notice: "Audio channel was successfully created." }
        format.json { render :show, status: :created, location: @audio_channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @audio_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audio_channels/1 or /audio_channels/1.json
  def update

    respond_to do |format|
      if @audio_channel.update(audio_channel_params)
        enteredNumber = @audio_channel.chNumber
        @audio_channel.update(chMcastIP: create_mcast_ip(enteredNumber))
        format.html { redirect_to @audio_channel, notice: "Audio channel was successfully updated." }
        format.json { render :show, status: :ok, location: @audio_channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @audio_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audio_channels/1 or /audio_channels/1.json
  def destroy
    @audio_channel.destroy
    respond_to do |format|
      format.html { redirect_to audio_channels_url, notice: "Audio channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_channel
      @audio_channel = AudioChannel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def audio_channel_params
      params.require(:audio_channel).permit(:chNumber, :chName, :chMcastIP, :chNotes)
    end

    # Create the multicast IP from the channel number.
    def create_mcast_ip(channelNumber)
      #TODO add math to create multicast IP
      #generate octect 3 in the IP address
      oct3 = (channelNumber / 256).floor
      #generate octect 4 in the IP address
      oct4 = channelNumber - oct3 * 256
      #create the entire IP address
      mcastIP = "239.192.#{oct3}.#{oct4}"
      return mcastIP
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_channels_helper.rb
module AudioChannelsHelper
end

app/views/audio_channels/_form.html.erb
<%= form_with(model: audio_channel) do |form| %>
  <% if audio_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(audio_channel.errors.count, "error") %> prohibited this audio_channel from being saved:</h2>

      <ul>
        <% audio_channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chNumber %>
    <%= form.number_field :chNumber %>
  </div>

  <div class="field">
    <%= form.label :chName %>
    <%= form.text_field :chName %>
  </div>


  <div class="field">
    <%= form.label :chNotes %>
    <%= form.text_area :chNotes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/audio_channels/edit.html.erb
<h1>Editing Audio Channel</h1>

<%= render 'form', audio_channel: @audio_channel %>

<%= link_to 'Show', @audio_channel %> |
<%= link_to 'Back', audio_channels_path %>

app/views/audio_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Audio Channels</h1>

<table>
  <thead>
    <tr>
      <th>Chnumber</th>
      <th>Chname</th>
      <th>Chmcastip</th>
      <th>Chnotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @audio_channels.each do |audio_channel| %>
      <tr>
        <td><%= audio_channel.chNumber %></td>
        <td><%= audio_channel.chName %></td>
        <td><%= audio_channel.chMcastIP %></td>
        <td><%= audio_channel.chNotes %></td>
        <td><%= link_to 'Show', audio_channel %></td>
        <td><%= link_to 'Edit', edit_audio_channel_path(audio_channel) %></td>
        <td><%= link_to 'Destroy', audio_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audio Channel', new_audio_channel_path %>

app/views/audio_channels/new.html.erb
<h1>New Audio Channel</h1>

<%= render 'form', audio_channel: @audio_channel %>

<%= link_to 'Back', audio_channels_path %>

app/views/audio_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chnumber:</strong>
  <%= @audio_channel.chNumber %>
</p>

<p>
  <strong>Chname:</strong>
  <%= @audio_channel.chName %>
</p>

<p>
  <strong>Chmcastip:</strong>
  <%= @audio_channel.chMcastIP %>
</p>

<p>
  <strong>Chnotes:</strong>
  <%= @audio_channel.chNotes %>
</p>

<%= link_to 'Edit', edit_audio_channel_path(@audio_channel) %> |
<%= link_to 'Back', audio_channels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LWParrot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>